### ISSUE TITLE
tips on styling

### ISSUE THREAD

**Issue by benswift** [sylvainmetayer/jekyll-fontawesome-svg#5]
I'm currently just using the standard fontawesome+svg thing on [my blog](http://benswift.me), and the js file I pull down switches out the e.g. `<i class="fab fa-github"></i>` nodes in my html for `<svg>` ones on page load.

I'd love to replace that with this gem's approach, but I'm having trouble with the styling. I guess I just figured that I'd replace `<i class="fab fa-github"></i>` with `{% fa_svg fab.fa-github %}`and I'd be done, but that's not how it's working out (they show up much too big, and not respecting the colours, etc.).

 I can eventually get colours & stuff working ok (by playing with css) but in particular it's sizing & alignment that isn't working the same. The fontawesome+svg stylesheet I was originally using also defines some styling for the inline svg elements such as this:

```css
.svg-inline--fa.fa-w-16 {
    width: 1em;
}
.svg-inline--fa {
    display: inline-block;
    font-size: inherit;
    height: 1em;
    overflow: visible;
    vertical-align: -.125em;
}
```
Is there a way to get this gem to do that automatically, or should I just find the appropriate styes and add them manually? Is there some better way to do this that I'm missing?
